/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as ApiPoolsRouteImport } from './routes/api/pools'
import { Route as PoolsIdRouteImport } from './routes/pools.$id'
import { Route as ApiPoolsIdRouteImport } from './routes/api/pools.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoolsRoute = ApiPoolsRouteImport.update({
  id: '/api/pools',
  path: '/api/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsIdRoute = PoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PoolsRoute,
} as any)
const ApiPoolsIdRoute = ApiPoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPoolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pools': typeof PoolsRouteWithChildren
  '/api/pools': typeof ApiPoolsRouteWithChildren
  '/pools/$id': typeof PoolsIdRoute
  '/api/pools/$id': typeof ApiPoolsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pools': typeof PoolsRouteWithChildren
  '/api/pools': typeof ApiPoolsRouteWithChildren
  '/pools/$id': typeof PoolsIdRoute
  '/api/pools/$id': typeof ApiPoolsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pools': typeof PoolsRouteWithChildren
  '/api/pools': typeof ApiPoolsRouteWithChildren
  '/pools/$id': typeof PoolsIdRoute
  '/api/pools/$id': typeof ApiPoolsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pools' | '/api/pools' | '/pools/$id' | '/api/pools/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pools' | '/api/pools' | '/pools/$id' | '/api/pools/$id'
  id:
    '__root__' | '/' | '/pools' | '/api/pools' | '/pools/$id' | '/api/pools/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoolsRoute: typeof PoolsRouteWithChildren
  ApiPoolsRoute: typeof ApiPoolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pools': {
      id: '/api/pools'
      path: '/api/pools'
      fullPath: '/api/pools'
      preLoaderRoute: typeof ApiPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$id': {
      id: '/pools/$id'
      path: '/$id'
      fullPath: '/pools/$id'
      preLoaderRoute: typeof PoolsIdRouteImport
      parentRoute: typeof PoolsRoute
    }
    '/api/pools/$id': {
      id: '/api/pools/$id'
      path: '/$id'
      fullPath: '/api/pools/$id'
      preLoaderRoute: typeof ApiPoolsIdRouteImport
      parentRoute: typeof ApiPoolsRoute
    }
  }
}

interface PoolsRouteChildren {
  PoolsIdRoute: typeof PoolsIdRoute
}

const PoolsRouteChildren: PoolsRouteChildren = {
  PoolsIdRoute: PoolsIdRoute,
}

const PoolsRouteWithChildren = PoolsRoute._addFileChildren(PoolsRouteChildren)

interface ApiPoolsRouteChildren {
  ApiPoolsIdRoute: typeof ApiPoolsIdRoute
}

const ApiPoolsRouteChildren: ApiPoolsRouteChildren = {
  ApiPoolsIdRoute: ApiPoolsIdRoute,
}

const ApiPoolsRouteWithChildren = ApiPoolsRoute._addFileChildren(
  ApiPoolsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoolsRoute: PoolsRouteWithChildren,
  ApiPoolsRoute: ApiPoolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
