import "dotenv/config";
import { getAuthedSdk } from "./bento.js";
import { addDuel } from "./state.js";

/**
 * Create exactly one public Pulse market. Confirmed more reliable than
 * generator.ts's batched loop against current platform flakiness — see
 * docs/BENTO_INTEGRATION.md finding #7. Use this directly while that's
 * still true; fold back into generator.ts once creation stabilizes.
 *
 * Usage: npm run create -- "Will there be a goal in the next half hour?"
 */

const LEAD_MINUTES = Number(process.env.PULSE_LEAD_MINUTES ?? 32);
// 3 hours for manual testing — the earlier 30min batch closed before anyone
// could finish testing against it (see BENTO_INTEGRATION.md finding #10).
const WINDOW_MINUTES = Number(process.env.PULSE_WINDOW_MINUTES ?? 180);
const HOME = process.env.DEMO_HOME_TEAM || "Argentina";
const AWAY = process.env.DEMO_AWAY_TEAM || "Brazil";

const question = process.argv[2] ?? `Will there be a goal? (${HOME} vs ${AWAY})`;

async function main() {
  const sdk = await getAuthedSdk();
  const now = Date.now();
  const startTime = new Date(now + LEAD_MINUTES * 60_000).toISOString();
  const endTime = new Date(now + LEAD_MINUTES * 60_000 + WINDOW_MINUTES * 60_000).toISOString();
  try {
    const created = await sdk.user.createDuel({
      question,
      type: "prediction",
      category: "Football",
      description: `Live in-match micro-market — ${HOME} vs ${AWAY}, auto-generated by Pulse.`,
      optionA: "Yes",
      optionB: "No",
      startTime,
      endTime,
      privacyAccess: "public",
      collateralMode: "credits",
    });
    const duelId = (created as any).raw?.duelId;
    console.log(`✅ SUCCESS: ${duelId} - ${question}`);
    await addDuel({ duelId, question, startTime: Date.parse(startTime), endTime: Date.parse(endTime), resolved: false });
  } catch (e: any) {
    console.log("❌ FAILED:", e?.sdkError?.message ?? e?.message);
  }
}

main();
