import "dotenv/config";
import { getAuthedSdk } from "./bento.js";
import { pickBatch, type MatchContext } from "./questions.js";
import { addDuel } from "./state.js";

/**
 * Generator loop — see docs/ARCHITECTURE.md. Creates a fresh batch of
 * micro-prop questions every tick, timed LEAD_MINUTES out.
 *
 * Switched to PUBLIC markets (see BENTO_INTEGRATION.md finding #8): private
 * markets turned out to be invite-walled at the READ level, even for their
 * own creator — `getDuelById` denies access without an invite/membership,
 * which breaks the "private markets behind a public swipe UI" design
 * entirely. Public markets have no such wall, at the cost of a much longer
 * ~31min minimum lead time instead of ~6min. Trading cadence for something
 * confirmed to actually work end-to-end. Window defaults to 30min — the
 * only window length that's reliably succeeded across all testing (see
 * BENTO_INTEGRATION.md finding #7); shorter windows have never been
 * confirmed to work.
 *
 * NOTE: creation is also intermittently flaky right now for reasons that
 * don't trace to any parameter we control (see finding #7) — expect some
 * ticks to fail outright. That's why every create is try/caught
 * individually rather than aborting the whole batch on one failure.
 */

const LEAD_MINUTES = Number(process.env.PULSE_LEAD_MINUTES ?? 32);
const WINDOW_MINUTES = Number(process.env.PULSE_WINDOW_MINUTES ?? 180); // 3hr for manual testing
const PRIVACY = (process.env.PULSE_PRIVACY as "public" | "private") ?? "public";
const BATCH_SIZE = Number(process.env.PULSE_BATCH_SIZE ?? 3);
const TICK_MS = Number(process.env.PULSE_TICK_MS ?? 120_000);

const MATCH: MatchContext = {
  home: process.env.DEMO_HOME_TEAM || "Argentina",
  away: process.env.DEMO_AWAY_TEAM || "Brazil",
};

async function generateOnce() {
  const sdk = await getAuthedSdk();
  const batch = pickBatch(MATCH, BATCH_SIZE);
  const now = Date.now();
  const startTime = new Date(now + LEAD_MINUTES * 60_000).toISOString();
  const endTime = new Date(now + LEAD_MINUTES * 60_000 + WINDOW_MINUTES * 60_000).toISOString();

  for (const tpl of batch) {
    const question = tpl.question(MATCH);
    try {
      const created = await sdk.user.createDuel({
        question,
        type: "prediction",
        category: tpl.category,
        description: `Live in-match micro-market — ${MATCH.home} vs ${MATCH.away}, auto-generated by Pulse.`,
        optionA: "Yes",
        optionB: "No",
        startTime,
        endTime,
        privacyAccess: PRIVACY,
        collateralMode: "credits",
      });
      const duelId = (created as any).raw?.duelId;
      console.log(`✅ created "${question}" -> ${duelId}`);
      await addDuel({
        duelId,
        question,
        startTime: Date.parse(startTime),
        endTime: Date.parse(endTime),
        resolved: false,
      });
    } catch (err: any) {
      console.error(`❌ failed to create "${question}":`, err?.sdkError?.message ?? err?.message);
    }
    // small stagger between creates in one batch — avoid bursting
    await new Promise((r) => setTimeout(r, 3_000));
  }
}

async function main() {
  console.log(
    `Pulse generator starting — lead=${LEAD_MINUTES}min window=${WINDOW_MINUTES}min privacy=${PRIVACY} batch=${BATCH_SIZE} tick=${TICK_MS / 1000}s`,
  );
  // eslint-disable-next-line no-constant-condition
  while (true) {
    await generateOnce().catch((e) => console.error("generateOnce crashed:", e));
    await new Promise((r) => setTimeout(r, TICK_MS));
  }
}

main();
