import "dotenv/config";
import { getAuthedSdk } from "./bento.js";

async function main() {
  const sdk = await getAuthedSdk();
  const now = Date.now();
  const startTime = new Date(now + 7 * 60_000).toISOString();
  const endTime = new Date(now + 7 * 60_000 + 30*60_000).toISOString();
  try {
    const created = await sdk.user.createDuel({
      question: "Will there be a goal in the next 5 minutes? (Argentina vs Brazil)",
      type: "prediction",
      category: "Football",
      description: "Live in-match micro-market — Argentina vs Brazil, auto-generated by Pulse.",
      optionA: "Yes",
      optionB: "No",
      startTime,
      endTime,
      privacyAccess: "private",
      collateralMode: "credits",
    });
    console.log("✅ SUCCESS:", (created as any).raw?.duelId);
  } catch (e: any) {
    console.log("❌ FAILED:", e?.sdkError?.message ?? e?.message, "| correlationId:", e?.sdkError?.correlationId);
  }
}

main();
